// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  IssueRefreshTokenData,
  IssueRefreshTokenResponses,
  RefreshAccessTokenData,
  RefreshAccessTokenResponses,
  AuthJwtLoginData,
  AuthJwtLoginResponses,
  AuthJwtLoginErrors,
  AuthJwtLogoutData,
  AuthJwtLogoutResponses,
  AuthJwtLogoutErrors,
  ResetForgotPasswordData,
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ResetResetPasswordData,
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  VerifyRequestTokenData,
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  VerifyVerifyData,
  VerifyVerifyResponses,
  VerifyVerifyErrors,
  UsersCurrentUserData,
  UsersCurrentUserResponses,
  UsersCurrentUserErrors,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUserData,
  UsersUserResponses,
  UsersUserErrors,
  UsersPatchUserData,
  UsersPatchUserResponses,
  UsersPatchUserErrors,
  ListSchedulerJobsData,
  ListSchedulerJobsResponses,
  ListSchedulerJobsErrors,
  CreateSchedulerJobData,
  CreateSchedulerJobResponses,
  CreateSchedulerJobErrors,
  DeleteSchedulerJobData,
  DeleteSchedulerJobResponses,
  DeleteSchedulerJobErrors,
  UpdateSchedulerJobData,
  UpdateSchedulerJobResponses,
  UpdateSchedulerJobErrors,
  EnqueueRunNowData,
  EnqueueRunNowResponses,
  EnqueueRunNowErrors,
  ListJobQueueData,
  ListJobQueueResponses,
  ListJobQueueErrors,
  CancelQueueItemData,
  CancelQueueItemResponses,
  CancelQueueItemErrors,
  ListJobLogsData,
  ListJobLogsResponses,
  ListJobLogsErrors,
  ClearStuckRunningLogAndEnqueueData,
  ClearStuckRunningLogAndEnqueueResponses,
  ClearStuckRunningLogAndEnqueueErrors,
  SearchCoursesData,
  SearchCoursesResponses,
  SearchCoursesErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Issue Refresh Token
 * Issue refresh token while access token is valid.
 * Frontend stores it in HTTP-only cookie.
 */
export const issueRefreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<IssueRefreshTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    IssueRefreshTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/refresh-token",
    ...options,
  });
};

/**
 * Refresh Access Token
 * Re-issue access token using refresh token from httpOnly cookie.
 */
export const refreshAccessToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshAccessTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RefreshAccessTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/jwt/refresh",
    ...options,
  });
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/logout",
    ...options,
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Scheduler Jobs
 */
export const listSchedulerJobs = <ThrowOnError extends boolean = false>(
  options?: Options<ListSchedulerJobsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSchedulerJobsResponses,
    ListSchedulerJobsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/jobs",
    ...options,
  });
};

/**
 * Create Scheduler Job
 */
export const createSchedulerJob = <ThrowOnError extends boolean = false>(
  options: Options<CreateSchedulerJobData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateSchedulerJobResponses,
    CreateSchedulerJobErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/jobs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Scheduler Job
 */
export const deleteSchedulerJob = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSchedulerJobData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteSchedulerJobResponses,
    DeleteSchedulerJobErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/jobs/{job_key}",
    ...options,
  });
};

/**
 * Update Scheduler Job
 */
export const updateSchedulerJob = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSchedulerJobData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UpdateSchedulerJobResponses,
    UpdateSchedulerJobErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/jobs/{job_key}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Enqueue Run Now
 */
export const enqueueRunNow = <ThrowOnError extends boolean = false>(
  options: Options<EnqueueRunNowData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    EnqueueRunNowResponses,
    EnqueueRunNowErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/jobs/{job_key}/enqueue-run",
    ...options,
  });
};

/**
 * List Job Queue
 */
export const listJobQueue = <ThrowOnError extends boolean = false>(
  options?: Options<ListJobQueueData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListJobQueueResponses,
    ListJobQueueErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/queue",
    ...options,
  });
};

/**
 * Cancel Queue Item
 */
export const cancelQueueItem = <ThrowOnError extends boolean = false>(
  options: Options<CancelQueueItemData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CancelQueueItemResponses,
    CancelQueueItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/queue/{queue_id}/cancel",
    ...options,
  });
};

/**
 * List Job Logs
 */
export const listJobLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListJobLogsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListJobLogsResponses,
    ListJobLogsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/job-logs",
    ...options,
  });
};

/**
 * Clear Stuck Running Log And Enqueue
 */
export const clearStuckRunningLogAndEnqueue = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ClearStuckRunningLogAndEnqueueData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ClearStuckRunningLogAndEnqueueResponses,
    ClearStuckRunningLogAndEnqueueErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/scheduler/job-logs/{log_id}/clear-stuck-and-enqueue",
    ...options,
  });
};

/**
 * Search Courses
 */
export const searchCourses = <ThrowOnError extends boolean = false>(
  options: Options<SearchCoursesData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    SearchCoursesResponses,
    SearchCoursesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/courses/search",
    ...options,
  });
};
