// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "./client";
import type {
  IssueRefreshTokenData,
  IssueRefreshTokenResponses,
  RefreshAccessTokenData,
  RefreshAccessTokenResponses,
  AuthJwtLoginData,
  AuthJwtLoginResponses,
  AuthJwtLoginErrors,
  AuthJwtLogoutData,
  AuthJwtLogoutResponses,
  AuthJwtLogoutErrors,
  ResetForgotPasswordData,
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ResetResetPasswordData,
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  VerifyRequestTokenData,
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  VerifyVerifyData,
  VerifyVerifyResponses,
  VerifyVerifyErrors,
  UsersCurrentUserData,
  UsersCurrentUserResponses,
  UsersCurrentUserErrors,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUserData,
  UsersUserResponses,
  UsersUserErrors,
  UsersPatchUserData,
  UsersPatchUserResponses,
  UsersPatchUserErrors,
  AdminListUsersData,
  AdminListUsersResponses,
  AdminListUsersErrors,
  AdminCreateUserData,
  AdminCreateUserResponses,
  AdminCreateUserErrors,
  AdminSetPasswordData,
  AdminSetPasswordResponses,
  AdminSetPasswordErrors,
  AdminUpdateUserData,
  AdminUpdateUserResponses,
  AdminUpdateUserErrors,
  ListPermissionResourcesData,
  ListPermissionResourcesResponses,
  GetUserPermissionsData,
  GetUserPermissionsResponses,
  GetUserPermissionsErrors,
  SaveUserPermissionsData,
  SaveUserPermissionsResponses,
  SaveUserPermissionsErrors,
  PermissionsMeData,
  PermissionsMeResponses,
  ListChannelsData,
  ListChannelsResponses,
  ListChannelsErrors,
  CreateChannelData,
  CreateChannelResponses,
  CreateChannelErrors,
  DeleteChannelData,
  DeleteChannelResponses,
  DeleteChannelErrors,
  GetChannelData,
  GetChannelResponses,
  GetChannelErrors,
  UpdateChannelData,
  UpdateChannelResponses,
  UpdateChannelErrors,
  ListCouriersData,
  ListCouriersResponses,
  ListCouriersErrors,
  CreateCourierData,
  CreateCourierResponses,
  CreateCourierErrors,
  DeleteCourierData,
  DeleteCourierResponses,
  DeleteCourierErrors,
  GetCourierData,
  GetCourierResponses,
  GetCourierErrors,
  UpdateCourierData,
  UpdateCourierResponses,
  UpdateCourierErrors,
  ListCategoriesData,
  ListCategoriesResponses,
  ListCategoriesErrors,
  CreateCategoryData,
  CreateCategoryResponses,
  CreateCategoryErrors,
  DeleteCategoryData,
  DeleteCategoryResponses,
  DeleteCategoryErrors,
  GetCategoryData,
  GetCategoryResponses,
  GetCategoryErrors,
  UpdateCategoryData,
  UpdateCategoryResponses,
  UpdateCategoryErrors,
  ListProductsData,
  ListProductsResponses,
  ListProductsErrors,
  CreateProductData,
  CreateProductResponses,
  CreateProductErrors,
  DeleteProductData,
  DeleteProductResponses,
  DeleteProductErrors,
  GetProductData,
  GetProductResponses,
  GetProductErrors,
  UpdateProductData,
  UpdateProductResponses,
  UpdateProductErrors,
  ListReceiversData,
  ListReceiversResponses,
  ListReceiversErrors,
  CreateReceiverData,
  CreateReceiverResponses,
  CreateReceiverErrors,
  DeleteReceiverData,
  DeleteReceiverResponses,
  DeleteReceiverErrors,
  GetReceiverData,
  GetReceiverResponses,
  GetReceiverErrors,
  UpdateReceiverData,
  UpdateReceiverResponses,
  UpdateReceiverErrors,
  ListOrdersData,
  ListOrdersResponses,
  ListOrdersErrors,
  CreateOrderData,
  CreateOrderResponses,
  CreateOrderErrors,
  ListAllOrderStatusOrdersData,
  ListAllOrderStatusOrdersResponses,
  DownloadOrdersExcelData,
  DownloadOrdersExcelResponses,
  DownloadOrdersExcelErrors,
  CountOrderPlacedOrdersData,
  CountOrderPlacedOrdersResponses,
  ListOrderHistoriesData,
  ListOrderHistoriesResponses,
  ListOrderHistoriesErrors,
  ListOrderHistoriesByOrderData,
  ListOrderHistoriesByOrderResponses,
  ListOrderHistoriesByOrderErrors,
  ListOrderMemosData,
  ListOrderMemosResponses,
  ListOrderMemosErrors,
  CreateOrderMemoData,
  CreateOrderMemoResponses,
  CreateOrderMemoErrors,
  DeleteOrderData,
  DeleteOrderResponses,
  DeleteOrderErrors,
  GetOrderData,
  GetOrderResponses,
  GetOrderErrors,
  UpdateOrderData,
  UpdateOrderResponses,
  UpdateOrderErrors,
  PlaceOrderData,
  PlaceOrderResponses,
  PlaceOrderErrors,
  PreviewExcelOrdersData,
  PreviewExcelOrdersResponses,
  PreviewExcelOrdersErrors,
  UploadExcelOrdersData,
  UploadExcelOrdersResponses,
  UploadExcelOrdersErrors,
  PreviewRawExportByChannelData,
  PreviewRawExportByChannelResponses,
  PreviewRawExportByChannelErrors,
  ExportRawByChannelData,
  ExportRawByChannelResponses,
  ExportRawByChannelErrors,
  ListShipmentsData,
  ListShipmentsResponses,
  ListShipmentsErrors,
  DownloadSelectedShipmentsExcelData,
  DownloadSelectedShipmentsExcelResponses,
  DownloadSelectedShipmentsExcelErrors,
  DownloadShipmentsExcelData,
  DownloadShipmentsExcelResponses,
  DownloadShipmentsExcelErrors,
  DownloadOrderPlacedExcelData,
  DownloadOrderPlacedExcelResponses,
  MarkOrderPlacedAsShippingWaitingData,
  MarkOrderPlacedAsShippingWaitingResponses,
  UploadInvoicesExcelData,
  UploadInvoicesExcelResponses,
  UploadInvoicesExcelErrors,
  ListSettlementsData,
  ListSettlementsResponses,
  ListSettlementsErrors,
  DownloadPendingSettlementsExcelData,
  DownloadPendingSettlementsExcelResponses,
  UploadSettlementExcelAndSettleData,
  UploadSettlementExcelAndSettleResponses,
  UploadSettlementExcelAndSettleErrors,
  CompleteSettlementData,
  CompleteSettlementResponses,
  CompleteSettlementErrors,
  RejectSettlementData,
  RejectSettlementResponses,
  RejectSettlementErrors,
  CompleteAllSettledData,
  CompleteAllSettledResponses,
  CompleteAllSettledErrors,
  RejectAllSettledData,
  RejectAllSettledResponses,
  RejectAllSettledErrors,
  ListProductAliasDictsData,
  ListProductAliasDictsResponses,
  ListProductAliasDictsErrors,
  CreateProductAliasDictData,
  CreateProductAliasDictResponses,
  CreateProductAliasDictErrors,
  DeleteProductAliasDictData,
  DeleteProductAliasDictResponses,
  DeleteProductAliasDictErrors,
  GetProductAliasDictData,
  GetProductAliasDictResponses,
  GetProductAliasDictErrors,
  UpdateProductAliasDictData,
  UpdateProductAliasDictResponses,
  UpdateProductAliasDictErrors,
  ListStocksData,
  ListStocksResponses,
  ListStocksErrors,
  CreateStockData,
  CreateStockResponses,
  CreateStockErrors,
  StockSummaryByProductData,
  StockSummaryByProductResponses,
  StockSummaryByProductErrors,
  StockSummaryByProductAndConditionData,
  StockSummaryByProductAndConditionResponses,
  StockSummaryByProductAndConditionErrors,
  ListAllStockHistoriesData,
  ListAllStockHistoriesResponses,
  ListAllStockHistoriesErrors,
  DeleteStockData,
  DeleteStockResponses,
  DeleteStockErrors,
  GetStockData,
  GetStockResponses,
  GetStockErrors,
  UpdateStockData,
  UpdateStockResponses,
  UpdateStockErrors,
  RestockData,
  RestockResponses,
  RestockErrors,
  ReleaseStockData,
  ReleaseStockResponses,
  ReleaseStockErrors,
  ChangeStockConditionData,
  ChangeStockConditionResponses,
  ChangeStockConditionErrors,
  TransferStockData,
  TransferStockResponses,
  TransferStockErrors,
  ListStockHistoriesData,
  ListStockHistoriesResponses,
  ListStockHistoriesErrors,
  ListLogisticsLocationsData,
  ListLogisticsLocationsResponses,
  ListLogisticsLocationsErrors,
  CreateLogisticsLocationData,
  CreateLogisticsLocationResponses,
  CreateLogisticsLocationErrors,
  DeleteLogisticsLocationData,
  DeleteLogisticsLocationResponses,
  DeleteLogisticsLocationErrors,
  GetLogisticsLocationData,
  GetLogisticsLocationResponses,
  GetLogisticsLocationErrors,
  UpdateLogisticsLocationData,
  UpdateLogisticsLocationResponses,
  UpdateLogisticsLocationErrors,
  GetLatestNoticeData,
  GetLatestNoticeResponses,
  CreateNoticeData,
  CreateNoticeResponses,
  CreateNoticeErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Issue Refresh Token
 * Issue refresh token while access token is valid.
 * Frontend stores it in HTTP-only cookie.
 */
export const issueRefreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<IssueRefreshTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    IssueRefreshTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/refresh-token",
    ...options,
  });
};

/**
 * Refresh Access Token
 * Re-issue access token using refresh token from httpOnly cookie.
 */
export const refreshAccessToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshAccessTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RefreshAccessTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/jwt/refresh",
    ...options,
  });
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/logout",
    ...options,
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Admin List Users
 */
export const adminListUsers = <ThrowOnError extends boolean = false>(
  options?: Options<AdminListUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AdminListUsersResponses,
    AdminListUsersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/users",
    ...options,
  });
};

/**
 * Admin Create User
 */
export const adminCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<AdminCreateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AdminCreateUserResponses,
    AdminCreateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Admin Set Password
 */
export const adminSetPassword = <ThrowOnError extends boolean = false>(
  options: Options<AdminSetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AdminSetPasswordResponses,
    AdminSetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/users/{user_id}/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Admin Update User
 */
export const adminUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<AdminUpdateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    AdminUpdateUserResponses,
    AdminUpdateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Permission Resources
 */
export const listPermissionResources = <ThrowOnError extends boolean = false>(
  options?: Options<ListPermissionResourcesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListPermissionResourcesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/permissions/resources",
    ...options,
  });
};

/**
 * Get User Permissions
 */
export const getUserPermissions = <ThrowOnError extends boolean = false>(
  options: Options<GetUserPermissionsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUserPermissionsResponses,
    GetUserPermissionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/permissions",
    ...options,
  });
};

/**
 * Save User Permissions
 */
export const saveUserPermissions = <ThrowOnError extends boolean = false>(
  options: Options<SaveUserPermissionsData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    SaveUserPermissionsResponses,
    SaveUserPermissionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/admin/permissions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Permissions Me
 */
export const permissionsMe = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionsMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PermissionsMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/permissions/me",
    ...options,
  });
};

/**
 * List Channels
 */
export const listChannels = <ThrowOnError extends boolean = false>(
  options?: Options<ListChannelsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListChannelsResponses,
    ListChannelsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/channels/",
    ...options,
  });
};

/**
 * Create Channel
 */
export const createChannel = <ThrowOnError extends boolean = false>(
  options: Options<CreateChannelData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateChannelResponses,
    CreateChannelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/channels/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Channel
 * 채널은 주문 데이터와 연계되므로 삭제할 수 없습니다.
 */
export const deleteChannel = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChannelData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteChannelResponses,
    DeleteChannelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/channels/{channel_id}",
    ...options,
  });
};

/**
 * Get Channel
 */
export const getChannel = <ThrowOnError extends boolean = false>(
  options: Options<GetChannelData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetChannelResponses,
    GetChannelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/channels/{channel_id}",
    ...options,
  });
};

/**
 * Update Channel
 */
export const updateChannel = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChannelData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateChannelResponses,
    UpdateChannelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/channels/{channel_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Couriers
 */
export const listCouriers = <ThrowOnError extends boolean = false>(
  options?: Options<ListCouriersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListCouriersResponses,
    ListCouriersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/couriers/",
    ...options,
  });
};

/**
 * Create Courier
 */
export const createCourier = <ThrowOnError extends boolean = false>(
  options: Options<CreateCourierData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateCourierResponses,
    CreateCourierErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/couriers/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Courier
 */
export const deleteCourier = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCourierData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteCourierResponses,
    DeleteCourierErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/couriers/{courier_id}",
    ...options,
  });
};

/**
 * Get Courier
 */
export const getCourier = <ThrowOnError extends boolean = false>(
  options: Options<GetCourierData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCourierResponses,
    GetCourierErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/couriers/{courier_id}",
    ...options,
  });
};

/**
 * Update Courier
 */
export const updateCourier = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCourierData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateCourierResponses,
    UpdateCourierErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/couriers/{courier_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Categories
 */
export const listCategories = <ThrowOnError extends boolean = false>(
  options?: Options<ListCategoriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListCategoriesResponses,
    ListCategoriesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/categories/",
    ...options,
  });
};

/**
 * Create Category
 */
export const createCategory = <ThrowOnError extends boolean = false>(
  options: Options<CreateCategoryData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateCategoryResponses,
    CreateCategoryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/categories/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Category
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCategoryData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteCategoryResponses,
    DeleteCategoryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/categories/{category_id}",
    ...options,
  });
};

/**
 * Get Category
 */
export const getCategory = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoryData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetCategoryResponses,
    GetCategoryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/categories/{category_id}",
    ...options,
  });
};

/**
 * Update Category
 */
export const updateCategory = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCategoryData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateCategoryResponses,
    UpdateCategoryErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/categories/{category_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Products
 */
export const listProducts = <ThrowOnError extends boolean = false>(
  options?: Options<ListProductsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListProductsResponses,
    ListProductsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/",
    ...options,
  });
};

/**
 * Create Product
 */
export const createProduct = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateProductResponses,
    CreateProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Product
 */
export const deleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductResponses,
    DeleteProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{product_id}",
    ...options,
  });
};

/**
 * Get Product
 */
export const getProduct = <ThrowOnError extends boolean = false>(
  options: Options<GetProductData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductResponses,
    GetProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{product_id}",
    ...options,
  });
};

/**
 * Update Product
 */
export const updateProduct = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProductData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateProductResponses,
    UpdateProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/products/{product_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Receivers
 */
export const listReceivers = <ThrowOnError extends boolean = false>(
  options?: Options<ListReceiversData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListReceiversResponses,
    ListReceiversErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/receivers/",
    ...options,
  });
};

/**
 * Create Receiver
 */
export const createReceiver = <ThrowOnError extends boolean = false>(
  options: Options<CreateReceiverData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateReceiverResponses,
    CreateReceiverErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/receivers/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Receiver
 */
export const deleteReceiver = <ThrowOnError extends boolean = false>(
  options: Options<DeleteReceiverData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteReceiverResponses,
    DeleteReceiverErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/receivers/{receiver_id}",
    ...options,
  });
};

/**
 * Get Receiver
 */
export const getReceiver = <ThrowOnError extends boolean = false>(
  options: Options<GetReceiverData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetReceiverResponses,
    GetReceiverErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/receivers/{receiver_id}",
    ...options,
  });
};

/**
 * Update Receiver
 */
export const updateReceiver = <ThrowOnError extends boolean = false>(
  options: Options<UpdateReceiverData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateReceiverResponses,
    UpdateReceiverErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/receivers/{receiver_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Orders
 */
export const listOrders = <ThrowOnError extends boolean = false>(
  options?: Options<ListOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListOrdersResponses,
    ListOrdersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/",
    ...options,
  });
};

/**
 * Create Order
 */
export const createOrder = <ThrowOnError extends boolean = false>(
  options: Options<CreateOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateOrderResponses,
    CreateOrderErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List All Order Status Orders
 * 발주(주문 → 발주) 기능 전용: ORDER 상태 주문을 한 번에 조회한다.
 * - 화면 페이지네이션 반복 호출을 금지하고, 서버에서 최대 1,000건으로 제한한다.
 */
export const listAllOrderStatusOrders = <ThrowOnError extends boolean = false>(
  options?: Options<ListAllOrderStatusOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAllOrderStatusOrdersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/order/all",
    ...options,
  });
};

/**
 * Download Orders Excel
 * 주문 엑셀 다운로드(xlsx).
 * - payload.order_ids가 있으면 해당 주문만 다운로드
 * - 없으면 query(filter) 조건으로 조회해 다운로드 (최대 10,000건)
 */
export const downloadOrdersExcel = <ThrowOnError extends boolean = false>(
  options?: Options<DownloadOrdersExcelData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    DownloadOrdersExcelResponses,
    DownloadOrdersExcelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/export/excel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Count Order Placed Orders
 */
export const countOrderPlacedOrders = <ThrowOnError extends boolean = false>(
  options?: Options<CountOrderPlacedOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CountOrderPlacedOrdersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/order-placed/count",
    ...options,
  });
};

/**
 * List Order Histories
 */
export const listOrderHistories = <ThrowOnError extends boolean = false>(
  options?: Options<ListOrderHistoriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListOrderHistoriesResponses,
    ListOrderHistoriesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/histories",
    ...options,
  });
};

/**
 * List Order Histories By Order
 */
export const listOrderHistoriesByOrder = <ThrowOnError extends boolean = false>(
  options: Options<ListOrderHistoriesByOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ListOrderHistoriesByOrderResponses,
    ListOrderHistoriesByOrderErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}/histories",
    ...options,
  });
};

/**
 * List Order Memos
 */
export const listOrderMemos = <ThrowOnError extends boolean = false>(
  options: Options<ListOrderMemosData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ListOrderMemosResponses,
    ListOrderMemosErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}/memos",
    ...options,
  });
};

/**
 * Create Order Memo
 */
export const createOrderMemo = <ThrowOnError extends boolean = false>(
  options: Options<CreateOrderMemoData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateOrderMemoResponses,
    CreateOrderMemoErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}/memos",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Order
 */
export const deleteOrder = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteOrderResponses,
    DeleteOrderErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}",
    ...options,
  });
};

/**
 * Get Order
 */
export const getOrder = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetOrderResponses,
    GetOrderErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}",
    ...options,
  });
};

/**
 * Update Order
 */
export const updateOrder = <ThrowOnError extends boolean = false>(
  options: Options<UpdateOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateOrderResponses,
    UpdateOrderErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Place Order
 */
export const placeOrder = <ThrowOnError extends boolean = false>(
  options: Options<PlaceOrderData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PlaceOrderResponses,
    PlaceOrderErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/place-order",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Preview Excel Orders
 */
export const previewExcelOrders = <ThrowOnError extends boolean = false>(
  options: Options<PreviewExcelOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PreviewExcelOrdersResponses,
    PreviewExcelOrdersErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/excel/preview",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Upload Excel Orders
 */
export const uploadExcelOrders = <ThrowOnError extends boolean = false>(
  options: Options<UploadExcelOrdersData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadExcelOrdersResponses,
    UploadExcelOrdersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/excel/upload",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Preview Raw Export By Channel
 */
export const previewRawExportByChannel = <ThrowOnError extends boolean = false>(
  options: Options<PreviewRawExportByChannelData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    PreviewRawExportByChannelResponses,
    PreviewRawExportByChannelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/export/raw-by-channel/preview",
    ...options,
  });
};

/**
 * Export Raw By Channel
 */
export const exportRawByChannel = <ThrowOnError extends boolean = false>(
  options: Options<ExportRawByChannelData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ExportRawByChannelResponses,
    ExportRawByChannelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/export/raw-by-channel",
    ...options,
  });
};

/**
 * List Shipments
 */
export const listShipments = <ThrowOnError extends boolean = false>(
  options?: Options<ListShipmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListShipmentsResponses,
    ListShipmentsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/shipments",
    ...options,
  });
};

/**
 * Download Selected Shipments Excel
 */
export const downloadSelectedShipmentsExcel = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DownloadSelectedShipmentsExcelData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    DownloadSelectedShipmentsExcelResponses,
    DownloadSelectedShipmentsExcelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/shipments/excel/selected",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Download Shipments Excel
 */
export const downloadShipmentsExcel = <ThrowOnError extends boolean = false>(
  options?: Options<DownloadShipmentsExcelData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    DownloadShipmentsExcelResponses,
    DownloadShipmentsExcelErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/shipments/excel",
    ...options,
  });
};

/**
 * Download Order Placed Excel
 */
export const downloadOrderPlacedExcel = <ThrowOnError extends boolean = false>(
  options?: Options<DownloadOrderPlacedExcelData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    DownloadOrderPlacedExcelResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/shipments/order-placed/excel",
    ...options,
  });
};

/**
 * Mark Order Placed As Shipping Waiting
 */
export const markOrderPlacedAsShippingWaiting = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MarkOrderPlacedAsShippingWaitingData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    MarkOrderPlacedAsShippingWaitingResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/shipments/order-placed/mark-shipping-waiting",
    ...options,
  });
};

/**
 * Upload Invoices Excel
 */
export const uploadInvoicesExcel = <ThrowOnError extends boolean = false>(
  options: Options<UploadInvoicesExcelData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadInvoicesExcelResponses,
    UploadInvoicesExcelErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/shipments/invoices/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * List Settlements
 */
export const listSettlements = <ThrowOnError extends boolean = false>(
  options?: Options<ListSettlementsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSettlementsResponses,
    ListSettlementsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements",
    ...options,
  });
};

/**
 * Download Pending Settlements Excel
 */
export const downloadPendingSettlementsExcel = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DownloadPendingSettlementsExcelData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    DownloadPendingSettlementsExcelResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements/pending/excel",
    ...options,
  });
};

/**
 * Upload Settlement Excel And Settle
 */
export const uploadSettlementExcelAndSettle = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UploadSettlementExcelAndSettleData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadSettlementExcelAndSettleResponses,
    UploadSettlementExcelAndSettleErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements/settle/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Complete Settlement
 */
export const completeSettlement = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSettlementData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CompleteSettlementResponses,
    CompleteSettlementErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements/{settlement_id}/complete",
    ...options,
  });
};

/**
 * Reject Settlement
 */
export const rejectSettlement = <ThrowOnError extends boolean = false>(
  options: Options<RejectSettlementData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RejectSettlementResponses,
    RejectSettlementErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements/{settlement_id}/reject",
    ...options,
  });
};

/**
 * Complete All Settled
 */
export const completeAllSettled = <ThrowOnError extends boolean = false>(
  options?: Options<CompleteAllSettledData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CompleteAllSettledResponses,
    CompleteAllSettledErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements/settled/complete-all",
    ...options,
  });
};

/**
 * Reject All Settled
 */
export const rejectAllSettled = <ThrowOnError extends boolean = false>(
  options?: Options<RejectAllSettledData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RejectAllSettledResponses,
    RejectAllSettledErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settlements/settled/reject-all",
    ...options,
  });
};

/**
 * List Product Alias Dicts
 */
export const listProductAliasDicts = <ThrowOnError extends boolean = false>(
  options?: Options<ListProductAliasDictsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListProductAliasDictsResponses,
    ListProductAliasDictsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-alias-dicts/",
    ...options,
  });
};

/**
 * Create Product Alias Dict
 */
export const createProductAliasDict = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductAliasDictData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateProductAliasDictResponses,
    CreateProductAliasDictErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-alias-dicts/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Product Alias Dict
 */
export const deleteProductAliasDict = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductAliasDictData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProductAliasDictResponses,
    DeleteProductAliasDictErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-alias-dicts/{alias_item_id}",
    ...options,
  });
};

/**
 * Get Product Alias Dict
 */
export const getProductAliasDict = <ThrowOnError extends boolean = false>(
  options: Options<GetProductAliasDictData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetProductAliasDictResponses,
    GetProductAliasDictErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-alias-dicts/{alias_item_id}",
    ...options,
  });
};

/**
 * Update Product Alias Dict
 */
export const updateProductAliasDict = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProductAliasDictData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateProductAliasDictResponses,
    UpdateProductAliasDictErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/product-alias-dicts/{alias_item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Stocks
 */
export const listStocks = <ThrowOnError extends boolean = false>(
  options?: Options<ListStocksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListStocksResponses,
    ListStocksErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/",
    ...options,
  });
};

/**
 * Create Stock
 */
export const createStock = <ThrowOnError extends boolean = false>(
  options: Options<CreateStockData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateStockResponses,
    CreateStockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Stock Summary By Product
 */
export const stockSummaryByProduct = <ThrowOnError extends boolean = false>(
  options?: Options<StockSummaryByProductData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StockSummaryByProductResponses,
    StockSummaryByProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/summary/by-product",
    ...options,
  });
};

/**
 * Stock Summary By Product And Condition
 */
export const stockSummaryByProductAndCondition = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<StockSummaryByProductAndConditionData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    StockSummaryByProductAndConditionResponses,
    StockSummaryByProductAndConditionErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/summary/by-product-and-condition",
    ...options,
  });
};

/**
 * List All Stock Histories
 */
export const listAllStockHistories = <ThrowOnError extends boolean = false>(
  options?: Options<ListAllStockHistoriesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAllStockHistoriesResponses,
    ListAllStockHistoriesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/histories",
    ...options,
  });
};

/**
 * Delete Stock
 */
export const deleteStock = <ThrowOnError extends boolean = false>(
  options: Options<DeleteStockData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteStockResponses,
    DeleteStockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}",
    ...options,
  });
};

/**
 * Get Stock
 */
export const getStock = <ThrowOnError extends boolean = false>(
  options: Options<GetStockData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetStockResponses,
    GetStockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}",
    ...options,
  });
};

/**
 * Update Stock
 */
export const updateStock = <ThrowOnError extends boolean = false>(
  options: Options<UpdateStockData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateStockResponses,
    UpdateStockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Restock
 */
export const restock = <ThrowOnError extends boolean = false>(
  options: Options<RestockData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    RestockResponses,
    RestockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}/restock",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Release Stock
 */
export const releaseStock = <ThrowOnError extends boolean = false>(
  options: Options<ReleaseStockData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    ReleaseStockResponses,
    ReleaseStockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}/release",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Change Stock Condition
 */
export const changeStockCondition = <ThrowOnError extends boolean = false>(
  options: Options<ChangeStockConditionData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    ChangeStockConditionResponses,
    ChangeStockConditionErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}/change-condition",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Transfer Stock
 */
export const transferStock = <ThrowOnError extends boolean = false>(
  options: Options<TransferStockData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    TransferStockResponses,
    TransferStockErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}/transfer",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Stock Histories
 */
export const listStockHistories = <ThrowOnError extends boolean = false>(
  options: Options<ListStockHistoriesData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ListStockHistoriesResponses,
    ListStockHistoriesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/stocks/{stock_id}/histories",
    ...options,
  });
};

/**
 * List Logistics Locations
 */
export const listLogisticsLocations = <ThrowOnError extends boolean = false>(
  options?: Options<ListLogisticsLocationsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListLogisticsLocationsResponses,
    ListLogisticsLocationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/logistics-locations/",
    ...options,
  });
};

/**
 * Create Logistics Location
 */
export const createLogisticsLocation = <ThrowOnError extends boolean = false>(
  options: Options<CreateLogisticsLocationData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateLogisticsLocationResponses,
    CreateLogisticsLocationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/logistics-locations/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Logistics Location
 */
export const deleteLogisticsLocation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteLogisticsLocationData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteLogisticsLocationResponses,
    DeleteLogisticsLocationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/logistics-locations/{location_id}",
    ...options,
  });
};

/**
 * Get Logistics Location
 */
export const getLogisticsLocation = <ThrowOnError extends boolean = false>(
  options: Options<GetLogisticsLocationData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetLogisticsLocationResponses,
    GetLogisticsLocationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/logistics-locations/{location_id}",
    ...options,
  });
};

/**
 * Update Logistics Location
 */
export const updateLogisticsLocation = <ThrowOnError extends boolean = false>(
  options: Options<UpdateLogisticsLocationData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateLogisticsLocationResponses,
    UpdateLogisticsLocationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/logistics-locations/{location_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Latest Notice
 */
export const getLatestNotice = <ThrowOnError extends boolean = false>(
  options?: Options<GetLatestNoticeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetLatestNoticeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/notices/latest",
    ...options,
  });
};

/**
 * Create Notice
 */
export const createNotice = <ThrowOnError extends boolean = false>(
  options: Options<CreateNoticeData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateNoticeResponses,
    CreateNoticeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/notices/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
