// This file is auto-generated by @hey-api/openapi-ts

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * CourseIndexResult
 */
export type CourseIndexResult = {
  /**
   * Fetched
   */
  fetched: number;
  /**
   * Indexed
   */
  indexed: number;
  /**
   * Total Count
   */
  total_count: number;
};

/**
 * CourseListItem
 */
export type CourseListItem = {
  /**
   * Trainst Cst Id
   */
  trainst_cst_id?: string | null;
  /**
   * Trpr Id
   */
  trpr_id?: string | null;
  /**
   * Trpr Degr
   */
  trpr_degr?: string | null;
  /**
   * Course Name
   */
  course_name?: string | null;
  /**
   * Inst Name
   */
  inst_name?: string | null;
  /**
   * Tra Start Date
   */
  tra_start_date?: string | null;
  /**
   * Tra End Date
   */
  tra_end_date?: string | null;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Tel No
   */
  tel_no?: string | null;
  /**
   * Title Link
   */
  title_link?: string | null;
  /**
   * Reg Course Man
   */
  reg_course_man?: string | null;
  /**
   * Yard Man
   */
  yard_man?: string | null;
  /**
   * Real Man
   */
  real_man?: string | null;
};

/**
 * CourseListResponse
 */
export type CourseListResponse = {
  /**
   * Items
   */
  items: Array<CourseListItem>;
  /**
   * Total Count
   */
  total_count: number;
  /**
   * Page Num
   */
  page_num: number;
  /**
   * Page Size
   */
  page_size: number;
};

/**
 * CourseSearchHit
 */
export type CourseSearchHit = {
  /**
   * Trpr Id
   */
  trpr_id?: string | null;
  /**
   * Trng Crse Nm
   */
  trng_crse_nm?: string | null;
  /**
   * Inst Nm
   */
  inst_nm?: string | null;
  /**
   * Score
   */
  score: number;
  [key: string]:
    | unknown
    | string
    | null
    | string
    | null
    | string
    | null
    | number
    | undefined;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LegacyIndexRequest
 */
export type LegacyIndexRequest = {
  /**
   * Start Month
   */
  start_month: string;
  /**
   * End Month
   */
  end_month: string;
};

/**
 * LegacyIndexResponse
 */
export type LegacyIndexResponse = {
  /**
   * Queue Ids
   */
  queue_ids: Array<number>;
  /**
   * Start Month
   */
  start_month: string;
  /**
   * End Month
   */
  end_month: string;
  /**
   * Month Count
   */
  month_count: number;
  /**
   * Message
   */
  message: string;
};

/**
 * Page[SchedulerJobLogRead]
 */
export type PageSchedulerJobLogRead = {
  /**
   * Items
   */
  items: Array<SchedulerJobLogRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * Page[SchedulerJobQueueRead]
 */
export type PageSchedulerJobQueueRead = {
  /**
   * Items
   */
  items: Array<SchedulerJobQueueRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * Page[Work24ApiLogRead]
 */
export type PageWork24ApiLogRead = {
  /**
   * Items
   */
  items: Array<Work24ApiLogRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * SchedulerJobCreate
 */
export type SchedulerJobCreate = {
  /**
   * Job Key
   */
  job_key: string;
  /**
   * Title
   */
  title: string;
  /**
   * Enabled
   */
  enabled?: boolean;
  /**
   * Cron Hour
   */
  cron_hour?: number;
  /**
   * Cron Minute
   */
  cron_minute?: number;
  /**
   * Timezone
   */
  timezone?: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * SchedulerJobLogRead
 */
export type SchedulerJobLogRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Job Id
   */
  job_id: string;
  /**
   * Started At
   */
  started_at: string;
  /**
   * Finished At
   */
  finished_at: string | null;
  /**
   * Status
   */
  status: string;
  /**
   * Elapsed Sec
   */
  elapsed_sec: number | null;
  /**
   * Error Message
   */
  error_message: string | null;
  /**
   * Detail
   */
  detail:
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
};

/**
 * SchedulerJobQueueRead
 */
export type SchedulerJobQueueRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Job Key
   */
  job_key: string;
  /**
   * Action
   */
  action: string;
  /**
   * Status
   */
  status: string;
  /**
   * Payload
   */
  payload?:
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
  /**
   * Requested By User Id
   */
  requested_by_user_id: string | null;
  /**
   * Related Log Id
   */
  related_log_id: number | null;
  /**
   * Error Message
   */
  error_message: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Started At
   */
  started_at: string | null;
  /**
   * Finished At
   */
  finished_at: string | null;
};

/**
 * SchedulerJobRead
 */
export type SchedulerJobRead = {
  /**
   * Job Key
   */
  job_key: string;
  /**
   * Title
   */
  title: string;
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Cron Hour
   */
  cron_hour: number;
  /**
   * Cron Minute
   */
  cron_minute: number;
  /**
   * Timezone
   */
  timezone: string;
  /**
   * Description
   */
  description: string | null;
};

/**
 * SchedulerJobUpdate
 */
export type SchedulerJobUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Enabled
   */
  enabled?: boolean | null;
  /**
   * Cron Hour
   */
  cron_hour?: number | null;
  /**
   * Cron Minute
   */
  cron_minute?: number | null;
  /**
   * Timezone
   */
  timezone?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Work24ApiLogRead
 */
export type Work24ApiLogRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Requested At
   */
  requested_at: string;
  /**
   * Method
   */
  method: string;
  /**
   * Url
   */
  url: string;
  /**
   * Request Headers
   */
  request_headers:
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
  /**
   * Response Status
   */
  response_status: number | null;
  /**
   * Response Headers
   */
  response_headers:
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
  /**
   * Context
   */
  context:
    | {
        [key: string]: unknown;
      }
    | Array<unknown>
    | null;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type IssueRefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/refresh-token";
};

export type IssueRefreshTokenResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RefreshAccessTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/refresh";
};

export type RefreshAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginResponse =
  AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ListSchedulerJobsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     * job_key 또는 title 검색
     */
    q?: string | null;
  };
  url: "/admin/scheduler/jobs";
};

export type ListSchedulerJobsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSchedulerJobsError =
  ListSchedulerJobsErrors[keyof ListSchedulerJobsErrors];

export type ListSchedulerJobsResponses = {
  /**
   * Response Admin-Scheduler-List Scheduler Jobs
   * Successful Response
   */
  200: Array<SchedulerJobRead>;
};

export type ListSchedulerJobsResponse =
  ListSchedulerJobsResponses[keyof ListSchedulerJobsResponses];

export type CreateSchedulerJobData = {
  body: SchedulerJobCreate;
  path?: never;
  query?: never;
  url: "/admin/scheduler/jobs";
};

export type CreateSchedulerJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSchedulerJobError =
  CreateSchedulerJobErrors[keyof CreateSchedulerJobErrors];

export type CreateSchedulerJobResponses = {
  /**
   * Successful Response
   */
  201: SchedulerJobRead;
};

export type CreateSchedulerJobResponse =
  CreateSchedulerJobResponses[keyof CreateSchedulerJobResponses];

export type DeleteSchedulerJobData = {
  body?: never;
  path: {
    /**
     * Job Key
     */
    job_key: string;
  };
  query?: never;
  url: "/admin/scheduler/jobs/{job_key}";
};

export type DeleteSchedulerJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteSchedulerJobError =
  DeleteSchedulerJobErrors[keyof DeleteSchedulerJobErrors];

export type DeleteSchedulerJobResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteSchedulerJobResponse =
  DeleteSchedulerJobResponses[keyof DeleteSchedulerJobResponses];

export type UpdateSchedulerJobData = {
  body: SchedulerJobUpdate;
  path: {
    /**
     * Job Key
     */
    job_key: string;
  };
  query?: never;
  url: "/admin/scheduler/jobs/{job_key}";
};

export type UpdateSchedulerJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateSchedulerJobError =
  UpdateSchedulerJobErrors[keyof UpdateSchedulerJobErrors];

export type UpdateSchedulerJobResponses = {
  /**
   * Successful Response
   */
  200: SchedulerJobRead;
};

export type UpdateSchedulerJobResponse =
  UpdateSchedulerJobResponses[keyof UpdateSchedulerJobResponses];

export type EnqueueRunNowData = {
  body?: never;
  path: {
    /**
     * Job Key
     */
    job_key: string;
  };
  query?: never;
  url: "/admin/scheduler/jobs/{job_key}/enqueue-run";
};

export type EnqueueRunNowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EnqueueRunNowError = EnqueueRunNowErrors[keyof EnqueueRunNowErrors];

export type EnqueueRunNowResponses = {
  /**
   * Successful Response
   */
  200: SchedulerJobQueueRead;
};

export type EnqueueRunNowResponse =
  EnqueueRunNowResponses[keyof EnqueueRunNowResponses];

export type ListJobQueueData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Job Key
     */
    job_key?: string | null;
    /**
     * Q
     * job_key 검색
     */
    q?: string | null;
  };
  url: "/admin/scheduler/queue";
};

export type ListJobQueueErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListJobQueueError = ListJobQueueErrors[keyof ListJobQueueErrors];

export type ListJobQueueResponses = {
  /**
   * Successful Response
   */
  200: PageSchedulerJobQueueRead;
};

export type ListJobQueueResponse =
  ListJobQueueResponses[keyof ListJobQueueResponses];

export type CancelQueueItemData = {
  body?: never;
  path: {
    /**
     * Queue Id
     */
    queue_id: number;
  };
  query?: never;
  url: "/admin/scheduler/queue/{queue_id}/cancel";
};

export type CancelQueueItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CancelQueueItemError =
  CancelQueueItemErrors[keyof CancelQueueItemErrors];

export type CancelQueueItemResponses = {
  /**
   * Successful Response
   */
  200: SchedulerJobQueueRead;
};

export type CancelQueueItemResponse =
  CancelQueueItemResponses[keyof CancelQueueItemResponses];

export type ListJobLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
    /**
     * Job Id
     */
    job_id?: string | null;
    /**
     * Status
     */
    status?: string | null;
  };
  url: "/admin/scheduler/job-logs";
};

export type ListJobLogsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListJobLogsError = ListJobLogsErrors[keyof ListJobLogsErrors];

export type ListJobLogsResponses = {
  /**
   * Successful Response
   */
  200: PageSchedulerJobLogRead;
};

export type ListJobLogsResponse =
  ListJobLogsResponses[keyof ListJobLogsResponses];

export type ClearStuckRunningLogAndEnqueueData = {
  body?: never;
  path: {
    /**
     * Log Id
     */
    log_id: number;
  };
  query?: {
    /**
     * Min Age Seconds
     */
    min_age_seconds?: number;
  };
  url: "/admin/scheduler/job-logs/{log_id}/clear-stuck-and-enqueue";
};

export type ClearStuckRunningLogAndEnqueueErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClearStuckRunningLogAndEnqueueError =
  ClearStuckRunningLogAndEnqueueErrors[keyof ClearStuckRunningLogAndEnqueueErrors];

export type ClearStuckRunningLogAndEnqueueResponses = {
  /**
   * Successful Response
   */
  200: SchedulerJobQueueRead;
};

export type ClearStuckRunningLogAndEnqueueResponse =
  ClearStuckRunningLogAndEnqueueResponses[keyof ClearStuckRunningLogAndEnqueueResponses];

export type ListCoursesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Srch Tra St Dt
     * 훈련시작일 From (YYYYMMDD 또는 YYYY-MM-DD)
     */
    srch_tra_st_dt: string;
    /**
     * Srch Tra End Dt
     * 훈련시작일 To (YYYYMMDD 또는 YYYY-MM-DD)
     */
    srch_tra_end_dt: string;
    /**
     * Srch Tra Organ Nm
     * 훈련기관명
     */
    srch_tra_organ_nm?: string | null;
    /**
     * Srch Tra Process Nm
     * 훈련과정명
     */
    srch_tra_process_nm?: string | null;
    /**
     * Page Num
     */
    page_num?: number;
    /**
     * Page Size
     */
    page_size?: number;
  };
  url: "/courses";
};

export type ListCoursesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCoursesError = ListCoursesErrors[keyof ListCoursesErrors];

export type ListCoursesResponses = {
  /**
   * Successful Response
   */
  200: CourseListResponse;
};

export type ListCoursesResponse =
  ListCoursesResponses[keyof ListCoursesResponses];

export type SearchCoursesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword
     */
    keyword: string;
    /**
     * Size
     */
    size?: number;
  };
  url: "/courses/search";
};

export type SearchCoursesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchCoursesError = SearchCoursesErrors[keyof SearchCoursesErrors];

export type SearchCoursesResponses = {
  /**
   * Response Courses-Search Courses
   * Successful Response
   */
  200: Array<CourseSearchHit>;
};

export type SearchCoursesResponse =
  SearchCoursesResponses[keyof SearchCoursesResponses];

export type IndexCoursesFromWork24Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/courses/index";
};

export type IndexCoursesFromWork24Responses = {
  /**
   * Successful Response
   */
  200: CourseIndexResult;
};

export type IndexCoursesFromWork24Response =
  IndexCoursesFromWork24Responses[keyof IndexCoursesFromWork24Responses];

export type EnqueueLegacyCourseIndexData = {
  body: LegacyIndexRequest;
  path?: never;
  query?: never;
  url: "/courses/legacy-index";
};

export type EnqueueLegacyCourseIndexErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EnqueueLegacyCourseIndexError =
  EnqueueLegacyCourseIndexErrors[keyof EnqueueLegacyCourseIndexErrors];

export type EnqueueLegacyCourseIndexResponses = {
  /**
   * Successful Response
   */
  200: LegacyIndexResponse;
};

export type EnqueueLegacyCourseIndexResponse =
  EnqueueLegacyCourseIndexResponses[keyof EnqueueLegacyCourseIndexResponses];

export type ListWork24ApiLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Response Status
     */
    response_status?: number | null;
    /**
     * Month
     * YYYY-MM
     */
    month?: string | null;
  };
  url: "/admin/work24-api-logs";
};

export type ListWork24ApiLogsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListWork24ApiLogsError =
  ListWork24ApiLogsErrors[keyof ListWork24ApiLogsErrors];

export type ListWork24ApiLogsResponses = {
  /**
   * Successful Response
   */
  200: PageWork24ApiLogRead;
};

export type ListWork24ApiLogsResponse =
  ListWork24ApiLogsResponses[keyof ListWork24ApiLogsResponses];

export type ClientOptions = {
  baseURL: `${string}://openapi.json` | (string & {});
};
