"""add ProductAliasDict.commission

Revision ID: 1271b08139ac
Revises: 7fcf0fe6b256
Create Date: 2026-04-21 17:31:56.117984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1271b08139ac'
down_revision: Union[str, None] = '7fcf0fe6b256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_alias_dicts', sa.Column('commission', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_alias_dicts', 'commission')
    # ### end Alembic commands ###
