"""add client_name_mappings

Revision ID: 1c0de19acb39
Revises: c8a3a205fbc9
Create Date: 2026-08-03 12:33:56.228669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1c0de19acb39'
down_revision: Union[str, None] = 'c8a3a205fbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_name_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name_mappings_client_name'), 'client_name_mappings', ['client_name'], unique=False)
    op.create_index(op.f('ix_client_name_mappings_institution_name'), 'client_name_mappings', ['institution_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_name_mappings_institution_name'), table_name='client_name_mappings')
    op.drop_index(op.f('ix_client_name_mappings_client_name'), table_name='client_name_mappings')
    op.drop_table('client_name_mappings')
    # ### end Alembic commands ###
