"""add consolidated order

Revision ID: 43202fba6872
Revises: f7d29d764ae2
Create Date: 2026-04-20 19:10:25.266870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '43202fba6872'
down_revision: Union[str, None] = 'f7d29d764ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('consolidated_to_order_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_orders_consolidated_to_order_id'), 'orders', ['consolidated_to_order_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'orders', ['consolidated_to_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_consolidated_to_order_id'), table_name='orders')
    op.drop_column('orders', 'consolidated_to_order_id')
    # ### end Alembic commands ###
