"""add owned_course_openings

Revision ID: 4c4ca8d6e137
Revises: 1c0de19acb39
Create Date: 2026-08-03 14:58:33.062708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4c4ca8d6e137'
down_revision: Union[str, None] = '1c0de19acb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owned_course_openings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('course_name', sa.String(length=500), nullable=True),
    sa.Column('tra_start_date', sa.Date(), nullable=True),
    sa.Column('tra_end_date', sa.Date(), nullable=True),
    sa.Column('reg_course_man', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owned_course_openings_year'), 'owned_course_openings', ['year'], unique=False)
    op.create_index('ix_owned_course_openings_year_tra_start', 'owned_course_openings', ['year', 'tra_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_owned_course_openings_year_tra_start', table_name='owned_course_openings')
    op.drop_index(op.f('ix_owned_course_openings_year'), table_name='owned_course_openings')
    op.drop_table('owned_course_openings')
    # ### end Alembic commands ###
