"""update product_alias_items set index

Revision ID: 5a0b160727f0
Revises: b6b00f37586f
Create Date: 2026-04-07 16:45:03.191114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5a0b160727f0'
down_revision: Union[str, None] = 'b6b00f37586f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_alias_items_alias_id'), 'product_alias_items', ['alias_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_alias_items_alias_id'), table_name='product_alias_items')
    # ### end Alembic commands ###
