"""add settlement management

Revision ID: 60eeee5504d1
Revises: d6e41319b94b
Create Date: 2026-04-09 17:49:29.580223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '60eeee5504d1'
down_revision: Union[str, None] = 'd6e41319b94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'SETTLED', 'COMPLETED', 'REJECT', 'CANCELLED', name='settlementstate'), nullable=False),
    sa.Column('update_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['update_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_order_id'), 'settlements', ['order_id'], unique=True)
    op.create_index(op.f('ix_settlements_state'), 'settlements', ['state'], unique=False)
    op.create_index('ix_settlements_state_created_at', 'settlements', ['state', 'created_at'], unique=False)
    op.create_table('settlement_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('CREATED', 'PRICE_UPDATED', 'STATE_CHANGED', 'CANCELLED_BY_ORDER', name='settlementhistoryactiontype'), nullable=False),
    sa.Column('update_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('from_state', sa.Enum('PENDING', 'SETTLED', 'COMPLETED', 'REJECT', 'CANCELLED', name='settlementstate'), nullable=True),
    sa.Column('to_state', sa.Enum('PENDING', 'SETTLED', 'COMPLETED', 'REJECT', 'CANCELLED', name='settlementstate'), nullable=True),
    sa.Column('before_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('after_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['update_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_histories_order_id'), 'settlement_histories', ['order_id'], unique=False)
    op.create_index(op.f('ix_settlement_histories_settlement_id'), 'settlement_histories', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_histories_update_user_id'), 'settlement_histories', ['update_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_histories_update_user_id'), table_name='settlement_histories')
    op.drop_index(op.f('ix_settlement_histories_settlement_id'), table_name='settlement_histories')
    op.drop_index(op.f('ix_settlement_histories_order_id'), table_name='settlement_histories')
    op.drop_table('settlement_histories')
    op.drop_index('ix_settlements_state_created_at', table_name='settlements')
    op.drop_index(op.f('ix_settlements_state'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_order_id'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
