"""add product_alias_dicts.channel column

Revision ID: 7fcf0fe6b256
Revises: 43202fba6872
Create Date: 2026-04-21 16:50:35.061880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7fcf0fe6b256'
down_revision: Union[str, None] = '43202fba6872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_alias_dicts', sa.Column('channel_id', sa.UUID(), nullable=True))
    op.drop_index('ix_product_alias_dicts_alias', table_name='product_alias_dicts')
    op.create_index(op.f('ix_product_alias_dicts_alias'), 'product_alias_dicts', ['alias'], unique=False)
    op.create_index(op.f('ix_product_alias_dicts_channel_id'), 'product_alias_dicts', ['channel_id'], unique=False)
    op.create_foreign_key(None, 'product_alias_dicts', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_alias_dicts', type_='foreignkey')
    op.drop_index(op.f('ix_product_alias_dicts_channel_id'), table_name='product_alias_dicts')
    op.drop_index(op.f('ix_product_alias_dicts_alias'), table_name='product_alias_dicts')
    op.create_index('ix_product_alias_dicts_alias', 'product_alias_dicts', ['alias'], unique=True)
    op.drop_column('product_alias_dicts', 'channel_id')
    # ### end Alembic commands ###
