"""add separate_settlements

Revision ID: 914a476ad9b3
Revises: 715e6661bf2c
Create Date: 2026-08-05 10:59:46.273383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '914a476ad9b3'
down_revision: Union[str, None] = '715e6661bf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('separate_settlements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice_deadline_date', sa.Date(), nullable=True),
    sa.Column('invoice_deadline_year', sa.Integer(), nullable=True),
    sa.Column('sales_rep', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('business_detail', sa.String(length=500), nullable=True),
    sa.Column('course_name', sa.String(length=500), nullable=False),
    sa.Column('base_revenue', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('settlement_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('settlement_rate_raw', sa.String(length=100), nullable=True),
    sa.Column('calculated_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('contract_period', sa.String(length=100), nullable=True),
    sa.Column('deduction_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invoice_item', sa.String(length=500), nullable=True),
    sa.Column('supply_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invoice_issuer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separate_settlements_client_name'), 'separate_settlements', ['client_name'], unique=False)
    op.create_index(op.f('ix_separate_settlements_course_name'), 'separate_settlements', ['course_name'], unique=False)
    op.create_index(op.f('ix_separate_settlements_invoice_deadline_date'), 'separate_settlements', ['invoice_deadline_date'], unique=False)
    op.create_index(op.f('ix_separate_settlements_invoice_deadline_year'), 'separate_settlements', ['invoice_deadline_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_separate_settlements_invoice_deadline_year'), table_name='separate_settlements')
    op.drop_index(op.f('ix_separate_settlements_invoice_deadline_date'), table_name='separate_settlements')
    op.drop_index(op.f('ix_separate_settlements_course_name'), table_name='separate_settlements')
    op.drop_index(op.f('ix_separate_settlements_client_name'), table_name='separate_settlements')
    op.drop_table('separate_settlements')
    # ### end Alembic commands ###
