"""add commission to oerders, settlement

Revision ID: b1c6782009ff
Revises: 1271b08139ac
Create Date: 2026-04-21 17:54:08.019524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b1c6782009ff'
down_revision: Union[str, None] = '1271b08139ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('commission', sa.Integer(), server_default='0', nullable=True))
    op.add_column('settlements', sa.Column('commission', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'commission')
    op.drop_column('orders', 'commission')
    # ### end Alembic commands ###
