"""add settlements.education_period_date 2

Revision ID: c8a3a205fbc9
Revises: 168011cd8daf
Create Date: 2026-08-03 11:42:57.270264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c8a3a205fbc9'
down_revision: Union[str, None] = '168011cd8daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('education_period_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'education_period_date')
    # ### end Alembic commands ###
