"""add company

Revision ID: cef6821d252c
Revises: 914a476ad9b3
Create Date: 2026-08-10 15:08:13.461358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cef6821d252c'
down_revision: Union[str, None] = '914a476ad9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.add_column('owned_course_openings', sa.Column('company_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_owned_course_openings_company_id'), 'owned_course_openings', ['company_id'], unique=False)
    op.create_index('ix_owned_course_openings_company_year', 'owned_course_openings', ['company_id', 'year'], unique=False)
    op.create_foreign_key(None, 'owned_course_openings', 'companies', ['company_id'], ['id'])
    op.add_column('owned_courses', sa.Column('company_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_owned_courses_company_id'), 'owned_courses', ['company_id'], unique=False)
    op.create_foreign_key(None, 'owned_courses', 'companies', ['company_id'], ['id'])
    op.add_column('owned_settlement_compare_results', sa.Column('company_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_owned_settlement_compare_results_company_id'), 'owned_settlement_compare_results', ['company_id'], unique=False)
    op.create_index('ix_owned_settlement_compare_results_company_year', 'owned_settlement_compare_results', ['company_id', 'year'], unique=False)
    op.create_foreign_key(None, 'owned_settlement_compare_results', 'companies', ['company_id'], ['id'])
    op.add_column('separate_settlements', sa.Column('company_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_separate_settlements_company_id'), 'separate_settlements', ['company_id'], unique=False)
    op.create_foreign_key(None, 'separate_settlements', 'companies', ['company_id'], ['id'])
    op.add_column('settlements', sa.Column('company_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_settlements_company_id'), 'settlements', ['company_id'], unique=False)
    op.create_foreign_key(None, 'settlements', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_index(op.f('ix_settlements_company_id'), table_name='settlements')
    op.drop_column('settlements', 'company_id')
    op.drop_constraint(None, 'separate_settlements', type_='foreignkey')
    op.drop_index(op.f('ix_separate_settlements_company_id'), table_name='separate_settlements')
    op.drop_column('separate_settlements', 'company_id')
    op.drop_constraint(None, 'owned_settlement_compare_results', type_='foreignkey')
    op.drop_index('ix_owned_settlement_compare_results_company_year', table_name='owned_settlement_compare_results')
    op.drop_index(op.f('ix_owned_settlement_compare_results_company_id'), table_name='owned_settlement_compare_results')
    op.drop_column('owned_settlement_compare_results', 'company_id')
    op.drop_constraint(None, 'owned_courses', type_='foreignkey')
    op.drop_index(op.f('ix_owned_courses_company_id'), table_name='owned_courses')
    op.drop_column('owned_courses', 'company_id')
    op.drop_constraint(None, 'owned_course_openings', type_='foreignkey')
    op.drop_index('ix_owned_course_openings_company_year', table_name='owned_course_openings')
    op.drop_index(op.f('ix_owned_course_openings_company_id'), table_name='owned_course_openings')
    op.drop_column('owned_course_openings', 'company_id')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
