"""update product_alias_dicts

Revision ID: d6e41319b94b
Revises: 5a0b160727f0
Create Date: 2026-04-07 17:33:09.183743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd6e41319b94b'
down_revision: Union[str, None] = '5a0b160727f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_alias_dicts', sa.Column('price', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_alias_dicts', 'price')
    # ### end Alembic commands ###
