"""add settlement settled_at, completed_at

Revision ID: f7d29d764ae2
Revises: 60eeee5504d1
Create Date: 2026-04-10 17:02:14.940225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f7d29d764ae2'
down_revision: Union[str, None] = '60eeee5504d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('settlements', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'completed_at')
    op.drop_column('settlements', 'settled_at')
    # ### end Alembic commands ###
